runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /img
  static_dir: img

- url: /stylesheets
  static_dir: stylesheets

- url: /javascripts
  static_dir: javascripts

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: numpy
  version: "1.6.1"
- name: matplotlib
  version: "1.2.0"

env_variables:
  GCS_BUCKET_NAME: 'oyomtstorage'

